"""empty message

Revision ID: 0a65a44f997e
Revises: 597ae3aa9057
Create Date: 2022-06-10 13:44:08.866827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a65a44f997e'
down_revision = '597ae3aa9057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created_date')
    # ### end Alembic commands ###
