"""empty message

Revision ID: 368ad07e3e83
Revises: 9f9e91d92554
Create Date: 2022-06-15 12:20:00.721999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368ad07e3e83'
down_revision = '9f9e91d92554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_idea_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_idea_id')
    # ### end Alembic commands ###
