"""empty message

Revision ID: 9f9e91d92554
Revises: 0a65a44f997e
Create Date: 2022-06-10 13:44:53.536750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9e91d92554'
down_revision = '0a65a44f997e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.drop_column('post', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_date', sa.DATETIME(), nullable=True))
    op.drop_column('post', 'created_time')
    # ### end Alembic commands ###
